In [102]:
import tensorflow as tf
import numpy as np

x = np.array([[0,0],[0,1],[1,0],[1,1]])


In [103]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [104]:
y = np.array([[0],[1],[1],[0]])
y

array([[0],
       [1],
       [1],
       [0]])

In [105]:
neuronios_entrada = 2
neuronios_oculta = 3
neuronios_saida = 1

In [106]:
# varivael peso na forma de dicionario
w = {'oculta': tf.Variable(tf.random_normal([neuronios_entrada,neuronios_oculta]), name = 'w_oculta'),
    'saida': tf.Variable(tf.random_normal([neuronios_oculta,neuronios_saida]), name = 'w_saida')}

In [107]:
w['oculta'] # matriz 2 linhas e 3 colunas

<tf.Variable 'w_oculta_6:0' shape=(2, 3) dtype=float32_ref>

In [108]:
w['saida'] # matriz 1 linha

<tf.Variable 'w_saida_6:0' shape=(3, 1) dtype=float32_ref>

In [109]:
b = {'oculta': tf.Variable(tf.random_normal([neuronios_oculta]), name = 'b_oculta'),
    'saida': tf.Variable(tf.random_normal([neuronios_saida]), name = 'b_saida')}

In [110]:
xph = tf.placeholder(tf.float32, [4,neuronios_entrada], name = 'xph') # construindo uma matriz 4x2
yph = tf.placeholder(tf.float32, [4, neuronios_saida], name = 'yph') # construindo uma matriz 4 linhas e 1 coluna

In [111]:
# sequencia do calculo de feedforward

# função soma ->Somatório de xi * wi + bias

camada_oculta = tf.add(tf.matmul(xph, w['oculta']), b['oculta'])

In [112]:
# Após o somatório, calcula-se a função de ativação

camada_oculta_ativacao = tf.sigmoid(camada_oculta)

In [113]:
#somatório da camdada de saida

camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, w['saida']), b['saida'])

In [114]:
#calculo da função de ativação na camada de saida

camada_saida_ativacao = tf.sigmoid(camada_saida)

In [131]:
# calculo do erro com o esperado e o previsto

erro = tf.losses.mean_squared_error(yph, camada_saida_ativacao)

In [132]:
# calculo do gradiente para otimizador

otimizador = tf.train.GradientDescentOptimizer(learning_rate = 0.3).minimize(erro)

In [115]:
init = tf.global_variables_initializer()

In [135]:
with tf.Session() as sess:
    sess.run(init)
#     print('Matriz de pesos entre entrada e camada oculta \n')
#     print(sess.run(w['oculta']))
#     print('\n')
#     print('Matriz de pesos entre camada oculta e saida \n')
#     print(sess.run(w['saida']))
#     print('\n')
#     print('Matriz de pesos bias oculta \n')
#     print(sess.run(b['oculta']))
#     print('\n')
#     print('Matriz de pesos bias saida \n')
#     print(sess.run(b['saida']))
#     print('Saida da função soma da entrada para camada oculta \n')
#     print(sess.run(camada_oculta, feed_dict = {xph: x}))
#     print('\nPara os somátorios os seguintes valores de ativação \n')
#     print(sess.run(camada_oculta_ativacao, feed_dict = {xph: x}))
#     print('\n')
#     print('Saida da função soma da entrada para camada oculta \n')
#     print(sess.run(camada_saida, feed_dict = {xph: x}))
#     print('\nPara os somátorios de saida os seguintes valores de ativação \n')
#     print(sess.run(camada_saida_ativacao, feed_dict = {xph: x}))
    for epocas in range (10000):
        erro_medio = 0
        _, custo = sess.run([otimizador, erro], feed_dict = {xph: x, yph: y})
        if epocas % 200 == 0: ## somente para mostra os primeiros 200 registros no print
            #print(custo)
            erro_medio += custo/4
            print(erro_medio) # conforme o treinamento avança o valor do erro diminui
    w_final, b_final = sess.run([w, b])

0.07311782240867615
0.06252825260162354
0.062511146068573
0.06250141561031342
0.06249452382326126
0.062487661838531494
0.062478207051754
0.062461789697408676
0.06242800131440163
0.06234602630138397
0.06211334094405174
0.06142248585820198
0.059750691056251526
0.05665087699890137
0.05190347135066986
0.046178173273801804
0.03971278294920921
0.03165864944458008
0.022565683349967003
0.01496255211532116
0.010001881048083305
0.007026735693216324
0.005211017560213804
0.004046289250254631
0.0032590008340775967
0.002701633144170046
0.0022913897410035133
0.001979504246264696
0.0017359217163175344
0.0015413369983434677
0.0013828919036313891
0.0012517432915046811
0.0011416557244956493
0.0010481025092303753
0.0009677446214482188
0.000898066908121109
0.0008371376898139715
0.0007834582356736064
0.0007358449511229992
0.00069335603620857
0.000655229261610657
0.0006208441336639225
0.0005896909278817475
0.0005613464745692909
0.000535458792001009
0.0005117279943078756
0.0004899033810943365
0.00046977007878

In [136]:
w_final

{'oculta': array([[ 1.8438222, -5.8453608,  3.77902  ],
        [ 1.8382725, -5.8427343,  3.7814682]], dtype=float32),
 'saida': array([[-2.8190084],
        [-8.645082 ],
        [-7.273337 ]], dtype=float32)}

In [137]:
b_final

{'oculta': array([-3.156663 ,  2.224952 , -5.9450684], dtype=float32),
 'saida': array([4.682876], dtype=float32)}

In [138]:
# teste

camada_oculta_teste = tf.add(tf.matmul(xph, w_final['oculta']), b_final['oculta'])
camada_oculta_ativacao_teste = tf.sigmoid(camada_oculta_teste)
camada_saida_teste = tf.add(tf.matmul(camada_oculta_ativacao_teste, w_final['saida']), b_final['saida'])
camada_saida_ativacao_teste = tf.sigmoid(camada_saida_teste)

In [139]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste,  feed_dict = {xph: x}))

[[0.03721458]
 [0.95739293]
 [0.9573771 ]
 [0.04083773]]
