In [111]:
import tensorflow as tf
import numpy as np

In [112]:
## Operador AND

x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [113]:
## Respostas operador AND

y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [114]:
pesos = tf.Variable(tf.zeros([2,1], dtype=tf.float64)) # duas entradas... dois pesos

In [115]:
def stepFunc(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x,1)), tf.float64)

In [116]:
init = tf.global_variables_initializer()

In [117]:
camada_saida = tf.matmul(x, pesos) # faz a parte do somatorio

In [118]:
camada_saida_ativacao = stepFunc(camada_saida)

In [119]:
erro = tf.subtract(y, camada_saida_ativacao)

In [120]:
delta = tf.matmul(x, erro, transpose_a = True)
treinamento = tf.add(pesos, tf.multiply(delta, 0.1)) # peso(n+1) = peso(n) + (tx_aprendizagem * x * erro)
pesos_novos = tf.assign(pesos, treinamento)

In [121]:
with tf.Session() as sess:
    sess.run(init)
#     print('Valor novo de pesos iniciais para x1 e x2')
#     print(sess.run(pesos))
#     print('\n saida dos somatorios para x1 e x2 e seus pesos')
#     print(sess.run(camada_saida)) # saida dos somatorios
#     print('\n saida da stepFunction')
#     print(sess.run(camada_saida_ativacao)) # as saidas deram todas como 0 pois é uma stepFunction
#     print('\n saidas com erro \n')
#     print(sess.run(erro)) # nota-se que para o ultimo valor o erro é 1
#     print('\n Valor novo de pesos para inserir')
#     print(sess.run(pesos_novos))

    print('\n execucao do treinamento')
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, pesos_novos])
        erro_soma = tf.reduce_sum(erro_total)
        #print(erro_total)
        print('Época:', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    peso_final = sess.run(pesos)


 execucao do treinamento
Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  1.0
Época: 6  Erro:  0.0


In [122]:
peso_final

array([[0.5],
       [0.5]])

In [123]:
# teste
camada_saida_teste = tf.matmul(x, peso_final)
camada_saida_ativacao_teste = stepFunc(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
