In [15]:
import tensorflow as tf
import numpy as np

In [16]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [17]:
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [18]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.variables.RefVariable

In [19]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [20]:
print(W)

<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float64_ref>


In [21]:
init = tf.global_variables_initializer()

In [22]:
camada_saida = tf.matmul(X, W)

In [23]:
camada_saida_ativacao = step(camada_saida)

In [24]:
erro = tf.subtract(y, camada_saida_ativacao)

In [25]:
delta = tf.matmul(X, erro, transpose_a = True)
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1)))

In [26]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(W))
    #print(sess.run(camada_saida))
    
    #print(sess.run(tf.to_float(tf.math.greater_equal(1, 1))))
    #print(sess.run(step(1)))
    #print('\n')
    #print(sess.run(camada_saida_ativacao))
    print('\n')
    #print(sess.run(erro))
    #print(X)
    #print('\n')
    #print(sess.run(tf.transpose(X)))
    #print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        #print(erro_total)
        print('Época:', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    W_final = sess.run(W)




Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  1.0
Época: 6  Erro:  0.0


In [27]:
W_final

array([[0.5],
       [0.5]])

In [28]:
# teste
camada_saida_teste = tf.matmul(X, W_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
