In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [5]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [8]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas) #Retirando colunas que nao sao necessárias
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [16]:
base.head() # o codigo acima realiza a normalização dos valores... (agora temos entre 0 e 1)

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [18]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']]) ## normalizando o Y

In [19]:
base.head() 

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [20]:
x = base.drop('price', axis=1) # atributos previsores
y = base.price # variável dependente

In [62]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [63]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [64]:
import tensorflow as tf
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas] # Feature colunm (recebendo o nome das colunas)

In [66]:
print(colunas[1])

NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [67]:
from sklearn.model_selection import train_test_split # separando base de dados, 70% treinamento e 30% teste
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x,y, test_size = 0.3)

In [68]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = x_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [69]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = x_teste, y = y_teste,
                                                        batch_size = 32, num_epochs = 10000, shuffle = False)

In [70]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Douglas\\AppData\\Local\\Temp\\tmp9la23xib', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000122715F0208>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [71]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Douglas\AppData\Local\Temp\tmp9la23xib\model.ckpt.
INFO:tensorflow:loss = 0.16111472, step = 1
INFO:tensorflow:global_step/sec: 300.279
INFO:tensorflow:loss = 0.01928353, step = 101 (0.335 sec)
INFO:tensorflow:global_step/sec: 411.491
INFO:tensorflow:loss = 0.04787059, step = 201 (0.243 sec)
INFO:tensorflow:global_step/sec: 411.492
INFO:tensorflow:loss = 0.028673846, step = 301 (0.244 sec)
INFO:tensorflow:global_step/sec: 404.827
INFO:tensorflow:loss = 0.01388442, step = 401 (0.246 sec)
INFO:tensorflow:global_step/sec: 408.132
INFO:tensorflow:loss = 0.015456385, step = 501 (0.245 sec)
INFO:tensorflow:global_step/sec: 408.13
INFO:tensorflow:loss = 0.020309467, step = 601 (0.244 sec)
INFO:tensorflow:g

INFO:tensorflow:loss = 0.017268768, step = 5501 (0.244 sec)
INFO:tensorflow:global_step/sec: 413.191
INFO:tensorflow:loss = 0.024264809, step = 5601 (0.243 sec)
INFO:tensorflow:global_step/sec: 413.191
INFO:tensorflow:loss = 0.014943542, step = 5701 (0.243 sec)
INFO:tensorflow:global_step/sec: 411.492
INFO:tensorflow:loss = 0.008938724, step = 5801 (0.242 sec)
INFO:tensorflow:global_step/sec: 420.135
INFO:tensorflow:loss = 0.026054561, step = 5901 (0.237 sec)
INFO:tensorflow:global_step/sec: 408.132
INFO:tensorflow:loss = 0.016882204, step = 6001 (0.246 sec)
INFO:tensorflow:global_step/sec: 416.635
INFO:tensorflow:loss = 0.021722125, step = 6101 (0.241 sec)
INFO:tensorflow:global_step/sec: 409.804
INFO:tensorflow:loss = 0.008718696, step = 6201 (0.243 sec)
INFO:tensorflow:global_step/sec: 409.805
INFO:tensorflow:loss = 0.029614119, step = 6301 (0.242 sec)
INFO:tensorflow:global_step/sec: 411.491
INFO:tensorflow:loss = 0.02339366, step = 6401 (0.246 sec)
INFO:tensorflow:global_step/sec:

In [72]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-03T11:28:35Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Douglas\AppData\Local\Temp\tmp9la23xib\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-08-03-11:28:59
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00071313424, global_step = 10000, label/mean = 0.060889967, loss = 0.022820296, prediction/mean = 0.05880614
INF

In [73]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-03T11:29:02Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Douglas\AppData\Local\Temp\tmp9la23xib\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-08-03-11:29:28
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00070453016, global_step = 10000, label/mean = 0.061243538, loss = 0.022544965, prediction/mean = 0.059397314
IN

In [74]:
metricas_treinamento

{'average_loss': 0.00071313424,
 'label/mean': 0.060889967,
 'loss': 0.022820296,
 'prediction/mean': 0.05880614,
 'global_step': 10000}

In [75]:
metricas_teste

{'average_loss': 0.00070453016,
 'label/mean': 0.061243538,
 'loss': 0.022544965,
 'prediction/mean': 0.059397314,
 'global_step': 10000}

In [76]:
 funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = x_teste, shuffle = False)

In [77]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [42]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Douglas\AppData\Local\Temp\tmpz8iz_2e0\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.03013713], dtype=float32)},
 {'predictions': array([0.10055459], dtype=float32)},
 {'predictions': array([0.02625464], dtype=float32)},
 {'predictions': array([0.04765333], dtype=float32)},
 {'predictions': array([0.10537799], dtype=float32)},
 {'predictions': array([0.01381813], dtype=float32)},
 {'predictions': array([0.01265918], dtype=float32)},
 {'predictions': array([0.02473828], dtype=float32)},
 {'predictions': array([0.02548116], dtype=float32)},
 {'predictions': array([0.05620655], dtype=float32)},
 {'predictions': array([0.09430753], dtype=float32)},
 {'predictions': array([0.03450981], dtype=float32)},
 {'predictions': array([0.03171378], dtype=float32)},
 {'predictions': array([0.01946166], dtype=float32)},
 {'predictions': array([0.04214985], dtype=float32)},
 {'predictions': array([0.00797731], dtype=float32)},
 {'predictions': array([0.05040181], dtype=float32)},
 {'predictions': array([0.03125881], dtype=float32)},
 {'predictions': array([0.04

In [78]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Douglas\AppData\Local\Temp\tmp9la23xib\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [49]:
valores_previsoes

[array([0.03013713], dtype=float32),
 array([0.10055459], dtype=float32),
 array([0.02625464], dtype=float32),
 array([0.04765333], dtype=float32),
 array([0.10537799], dtype=float32),
 array([0.01381813], dtype=float32),
 array([0.01265918], dtype=float32),
 array([0.02473828], dtype=float32),
 array([0.02548116], dtype=float32),
 array([0.05620655], dtype=float32),
 array([0.09430753], dtype=float32),
 array([0.03450981], dtype=float32),
 array([0.03171378], dtype=float32),
 array([0.01946166], dtype=float32),
 array([0.04214985], dtype=float32),
 array([0.00797731], dtype=float32),
 array([0.05040181], dtype=float32),
 array([0.03125881], dtype=float32),
 array([0.04471002], dtype=float32),
 array([0.02854384], dtype=float32),
 array([0.03179834], dtype=float32),
 array([0.02761012], dtype=float32),
 array([0.0620162], dtype=float32),
 array([0.01271185], dtype=float32),
 array([0.04059144], dtype=float32),
 array([0.00440671], dtype=float32),
 array([0.03187889], dtype=float32),
 a

In [79]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)
valores_previsoes

array([[ 0.03627355],
       [ 0.02182156],
       [ 0.07170781],
       ...,
       [ 0.03921537],
       [-0.0090939 ],
       [ 0.00170879]], dtype=float32)

In [80]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[351585.8   ],
       [241389.39  ],
       [621772.06  ],
       ...,
       [374017.22  ],
       [  5659.0464],
       [ 88029.53  ]], dtype=float32)

In [81]:
y_teste.shape

(6484,)

In [82]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [83]:
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

array([[410000.],
       [348000.],
       [625000.],
       ...,
       [417838.],
       [171500.],
       [281000.]])

In [85]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [86]:
mae

124287.4014338141